// An unknown flag is a REFUSAL, never a silent drop.
//
// kit#67 found this at `kit.js`, which accepted every flag it did not have and
// dropped it without a word — so `node kit.js kit --dir /elsewhere` printed a
// confident report about Kit's own corpus and nothing in the output said the flag
// had been ignored. kit#68 fixed that one entry point. It did not fix the others,
// and there are seven of them (this said "six" until 2026-10-01, while listing
// seven — `kit.test.js`'s ENTRY_POINTS derives the population instead of counting
// it by hand, which is why the test has always said seven):
//
//   requires.js   user-facing, and `--check` is a GATE
//   project.js    user-facing — the read model the UI is built on
//   saturation.js `--check` gates a committed document
//   self-host.js  `--check` gates a committed document
//   converge.js   a measurement that gets quoted
//   prose-audit.js a measurement that gets quoted
//   writer.js     WRITES to a corpus
//
// ⚠️ That list is the population kit#72 fixed, NOT every tool in this directory.
// `measure-tagging.js`, `compare.js`, `mutate.js` and `mutate-ui.js` still accept
// any flag silently — none of them requires this file (measured: `grep -c
// "require('./cli.js')"` is 0 in all four). The sharp one is `mutate.js --recoverr`,
// which does not recover: it starts a destructive five-and-a-half-minute mutation
// run, which then adopts whatever live mutant is in the tree as its pristine
// baseline. Tracked on kit#67; the fix waits on kit#96 because a third branch
// touching `kit.test.js` conflicts with it.
//
// 🔑 The reason this matters more than a usability nit: every one of those tools
// exists to answer a question about a NAMED artefact, and a dropped flag makes it
// answer about a different artefact with no change in how the answer looks. The
// measured case is `requires.js snip-it --check --dir <elsewhere>`, which reports
// 16 nouns and exits 1 about Kit's own corpus while naming yours; and
// `requires.js snip-it --dir /no/such/dir`, which exits 0 with a full report about
// a directory that cannot exist.
//
// ⚠️ This does NOT give any tool a flag it lacks. `kit.js:1187` deferred whether
// `kit.js` should GAIN `--dir` to James, on the grounds that a relocated corpus
// takes the noun namespace out of the only directory `sharedWith` can see, and
// that deferral stands here: refusing a flag makes its absence loud and pre-empts
// nothing. A tool that refuses `--dir` is telling you the truth; a tool that
// swallows it is not.
//
// Deliberately NOT a parser. `check.js:94` and `kit.js:1196` each have a full
// positional parser with this rule inside it, and folding all three into one is
// the right end state — but it re-anchors seven mutants and consolidating two
// mutation-covered parsers is an architecture call rather than a fix. So this is
// the one rule, callable, and the parsers stay where they are.

// Does this token mean "a flag" rather than "a value"? ONE dash is enough.
//
// A lone `-` is the stdin convention, not a flag. No tool here uses it; it is
// excluded so that adding one later does not start by tripping over this.
//
// ⚠️ This used to be three predicates, and a comment here claiming they agreed.
// That comment said a value starting with `-` "is reported rather than accepted,
// which is the same call `check.js:99` and `kit.js:1208` make". Both hand-written
// parsers tested `startsWith('--')` instead, so neither made that call, and
// `kit.js`'s `parseCliArgs` used one dash for the unknown-flag test and two for the
// forgotten-value test — inconsistent inside one function. The prose described an
// intention nothing implemented [[comments-are-a-plan-not-a-record]]. Measured, on
// `dev` @ `67c0c65`:
//
//   $ node kit.js sheet kit --rev -h
//   rc=0 ... Generated by `node kit.js sheet kit --rev -h`, over the app at `-h`.
//
// `--rev` lost its value, `-h` was eaten as the revision, and the provenance line
// of a committed sheet — the one line a reader can check it against — named a flag
// as the app's revision, at exit 0. One token earlier is refused correctly
// (`--rev` with nothing after it says "needs a value"), so the parsers caught a
// MISSING value and not a SWALLOWED one.
//
// So it is one function now, exported, and `kit.test.js`'s "ONE dash makes a token
// a flag" gate drives both hand-written parsers through it. This is NOT the parser
// consolidation the comment below defers: the parsers stay where they are and keep
// their own positional rules. Only the predicate is shared.
function looksLikeAFlag(token) {
  return typeof token === 'string' && token.startsWith('-') && token !== '-';
}

// The first token that looks like a flag and is not in `known`, else null.
//
// A value that itself starts with `-` is reported rather than accepted: `--dir
// --check` means the value was forgotten, and consuming the next flag as a path is
// how a gate ends up pointed somewhere nobody named.
function unknownFlag(argv, known) {
  const set = known instanceof Set ? known : new Set(known);
  for (const a of argv) {
    if (!looksLikeAFlag(a)) continue;
    if (set.has(a)) continue;
    return a;
  }
  return null;
}

// What a refusal says. One phrasing, because six tools saying it six ways is how
// the next reader concludes it is a different kind of problem in each.
// `cannot look` is `check.js:120`'s and `kit.js`'s existing wording for exit 2 —
// the three-valued rule, where a refusal is never conflated with a pass.
function refuse(flag, usage) {
  process.stderr.write(`cannot look: unknown option ${flag}\n`);
  if (usage) process.stderr.write(`${usage}\n`);
  return 2;
}

module.exports = { looksLikeAFlag, unknownFlag, refuse };
