using System.Text.Json.Nodes;
using Balenthiran.Kit.Database;
using Balenthiran.Kit.Services;

namespace Balenthiran.Kit.Tests;

/// <summary>
/// <c>kit report</c> and <c>kit sheet</c> scored against NODE: <c>Fixtures/Check/report-goldens.json</c>
/// is what <c>kit.js</c> printed and how it exited, as a real process, over a frozen copy of every
/// committed corpus and the refusals. Regenerate with <c>node prototypes/behaviour-ast/report-goldens.js</c>.
/// </summary>
/// <remarks>
/// Three substitutions, all on the Node side and all naming the command rather than changing what
/// it says: the usage line, and the sheet's "Generated by" line, name <c>kit</c> rather than
/// <c>node kit.js</c>; and each run's temp directory is <c>&lt;root&gt;</c> on both sides.
/// </remarks>
public class ReportCliConformanceTests
{
    private const string NodeUsage = "usage: node kit.js [sheet] [<corpus-name>] [--rev <rev>] [--dir <corpus-dir>]";

    private static readonly JsonNode Golden =
        JsonNode.Parse(File.ReadAllText(Path.Combine(RepoLayout.Fixtures, "Check", "report-goldens.json")))!;

    public static TheoryData<string> Cases()
    {
        var data = new TheoryData<string>();
        foreach (var c in Golden["checks"]!.AsArray())
        {
            data.Add(c!["name"]!.GetValue<string>());
        }

        return data;
    }

    /// <summary>A theory over an empty population reports green. These are the floors the golden was recorded with.</summary>
    [Fact]
    public void The_golden_still_holds_its_cases()
    {
        var checks = Golden["checks"]!.AsArray();
        Assert.True(checks.Count >= 43);
        Assert.True(checks.Count(c => c!["name"]!.GetValue<string>().StartsWith("sheet-", StringComparison.Ordinal)) >= 14);
        Assert.True(Golden["sets"]!["real"]!.AsObject().Count >= 15);
        Assert.Equal([0, 1, 2], checks.Select(c => c!["exitCode"]!.GetValue<int>()).ToHashSet().Order());
    }

    [Theory]
    [MemberData(nameof(Cases))]
    public void The_command_prints_and_exits_as_Node_did(string name)
    {
        var c = Golden["checks"]!.AsArray().Single(x => x!["name"]!.GetValue<string>() == name)!;
        var files = c["set"] is { } set ? Golden["sets"]![set.GetValue<string>()]!.AsObject() : c["files"]!.AsObject();
        var root = Directory.CreateTempSubdirectory("kit-report-").FullName;
        try
        {
            foreach (var (rel, text) in files)
            {
                var path = Path.Combine(root, rel);
                Directory.CreateDirectory(Path.GetDirectoryName(path)!);
                File.WriteAllText(path, text!.GetValue<string>());
            }

            var args = c["args"]!.AsArray().Select(a => a!.GetValue<string>()).ToList();
            var sheet = args.Count > 0 && args[0] == "sheet";
            var report = new KitReport(new CorpusParser(), new BehaviourResolver(), new TestGenerator(), new ProjectReporter(), new QuestionSheet(), new CheckFileSystem(root));
            var run = report.Run(sheet ? args.Skip(1).ToList() : args, sheet);

            string Named(string s) => s.Replace(NodeUsage, KitReport.Usage, StringComparison.Ordinal)
                .Replace("`node kit.js sheet ", "`kit sheet ", StringComparison.Ordinal);
            string Rooted(string s) => s.Replace(root, "<root>", StringComparison.Ordinal);

            Assert.Equal(Named(c["stdout"]!.GetValue<string>()), Rooted(run.Stdout));
            Assert.Equal(Named(c["stderr"]!.GetValue<string>()), Rooted(run.Stderr));
            Assert.Equal(c["exitCode"]!.GetValue<int>(), run.ExitCode);
        }
        finally
        {
            Directory.Delete(root, recursive: true);
        }
    }
}
